name: CD Deploy Backend

on:
  workflow_run:
    workflows: ["CI Backend Test pipeline"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: docker build -t backend-app .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - run: |
        aws ecr get-login-password --region us-east-1 |
        docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

    - run: |
        docker tag backend-app:latest ${{ secrets.ECR_URL }}:latest
        docker push ${{ secrets.ECR_URL }}:latest

    - uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.ECR_URL }}:latest
          docker stop backend || true
          docker rm backend || true
          docker run -d -p 3000:3000 --name backend ${{ secrets.ECR_URL }}:latest
